export const knowledgeBase = {
    "fever": ["flu", "malaria", "dengue", "typhoid", "COVID-19", "pneumonia"],
    "cough": ["flu", "cold", "tuberculosis", "bronchitis", "COVID-19", "asthma"],
    "headache": ["flu", "malaria", "cold", "migraine", "sinusitis", "COVID-19"],
    "sore throat": ["flu", "cold", "strep throat", "COVID-19"],
    "fatigue": ["flu", "malaria", "anemia", "COVID-19", "depression"],
    "chills": ["flu", "malaria", "dengue", "COVID-19"],
    "nausea": ["flu", "gastroenteritis", "food poisoning", "typhoid"],
    "vomiting": ["flu", "gastroenteritis", "food poisoning", "typhoid"],
    "diarrhea": ["gastroenteritis", "food poisoning", "cholera", "typhoid"],
    "muscle pain": ["flu", "dengue", "COVID-19", "fibromyalgia"],
    "sneezing": ["cold", "allergy", "hay_fever"],
    "chest pain": ["heart attack", "angina", "pneumonia", "pulmonary embolism"],
    "shortness of breath": ["asthma", "COPD", "heart failure", "pulmonary embolism"],
    "abdominal pain": ["appendicitis", "gallstones", "kidney stones", "ulcers"],
    "rash": ["measles", "chickenpox", "allergic reaction", "eczema"],
    "joint pain": ["arthritis", "lupus", "gout", "lyme disease"],
    "swollen lymph nodes": ["infection", "lymphoma", "HIV", "mononucleosis"],
    "weight loss": ["cancer", "diabetes", "hyperthyroidism", "HIV"],
    "night sweats": ["tuberculosis", "lymphoma", "menopause", "hyperthyroidism"]
};

export const medicineRecommendations = {
    "flu": ["Paracetamol", "Rest", "Fluids"],
    "malaria": ["Chloroquine", "Artemisinin-based combination therapies (ACTs)"],
    "dengue": ["Acetaminophen", "Hydration", "Rest"],
    "typhoid": ["Antibiotics", "Fluids", "Rest"],
    "cold": ["Antihistamines", "Decongestants", "Rest"],
    "tuberculosis": ["Isoniazid", "Rifampin", "Pyrazinamide"],
    "bronchitis": ["Cough syrup", "Bronchodilators", "Rest"],
    "migraine": ["Pain relievers", "Triptans", "Anti-nausea medications"],
    "sinusitis": ["Nasal corticosteroids", "Decongestants", "Pain relievers"],
    "food_poisoning": ["Oral rehydration solutions", "Antibiotics (for bacterial infections)"],
    "pregnancy": ["Prenatal vitamins", "Iron supplements", "Folic acid"],
    "allergy": ["Antihistamines", "Decongestants", "Corticosteroids"],
    "hay_fever": ["Antihistamines", "Nasal sprays", "Eye drops"],
    "anemia": ["Iron supplements", "Vitamin B12", "Folic acid"],
    "diabetes": ["Insulin", "Metformin", "Diet control"],
    "thyroid_problems": ["Levothyroxine", "Methimazole", "Beta blockers"],
    "heart_attack": ["Aspirin", "Nitroglycerin", "Beta blockers"],
    "angina": ["Nitrates", "Beta blockers", "Calcium channel blockers"],
    "pneumonia": ["Antibiotics", "Cough medicine", "Fever reducers"],
    "pulmonary_embolism": ["Anticoagulants", "Thrombolytics", "Compression stockings"],
    "asthma": ["Inhalers", "Corticosteroids", "Bronchodilators"],
    "COPD": ["Bronchodilators", "Steroids", "Oxygen therapy"],
    "heart_failure": ["Diuretics", "ACE inhibitors", "Beta blockers"],
    "appendicitis": ["Antibiotics", "Surgery"],
    "gallstones": ["Pain relievers", "Surgery", "Ursodeoxycholic acid"],
    "kidney_stones": ["Pain relievers", "Hydration", "Alpha blockers"],
    "ulcers": ["Proton pump inhibitors", "Antacids", "Antibiotics (for H. pylori)"],
    "gastroenteritis": ["Oral rehydration solutions", "Rest"],
    "IBS": ["Fiber supplements", "Antispasmodics", "Probiotics"],
    "Crohn's_disease": ["Anti-inflammatory drugs", "Immunosuppressants", "Biologics"],
    "measles": ["Fever reducers", "Vitamin A", "Rest"],
    "chickenpox": ["Antihistamines", "Antivirals", "Calamine lotion"],
    "allergic_reaction": ["Antihistamines", "Epinephrine (for severe reactions)"],
    "eczema": ["Moisturizers", "Corticosteroids", "Antihistamines"],
    "arthritis": ["Pain relievers", "Anti-inflammatory drugs", "Physical therapy"],
    "lupus": ["NSAIDs", "Corticosteroids", "Immunosuppressants"],
    "gout": ["NSAIDs", "Colchicine", "Corticosteroids"],
    "lyme_disease": ["Antibiotics", "Pain relievers"],
    "infection": ["Antibiotics", "Antivirals", "Antifungals"],
    "lymphoma": ["Chemotherapy", "Radiation therapy"],
    "HIV": ["Antiretrovirals", "Antibiotics (for opportunistic infections)"],
    "mononucleosis": ["Pain relievers", "Fluids", "Rest"],
    "cancer": ["Chemotherapy", "Radiation therapy", "Surgery"],
    "hyperthyroidism": ["Antithyroid medications", "Beta blockers", "Radioactive iodine"],
    "menopause": ["Hormone replacement therapy", "Calcium supplements", "Vitamin D"]
};

export const doctorTypes = {
    "flu": ["General Practitioner", "Family Medicine Doctor"],
    "malaria": ["Infectious Disease Specialist", "General Practitioner"],
    "dengue": ["Infectious Disease Specialist", "General Practitioner"],
    "typhoid": ["Infectious Disease Specialist", "General Practitioner"],
    "cold": ["General Practitioner", "Otolaryngologist"],
    "tuberculosis": ["Pulmonologist", "Infectious Disease Specialist"],
    "bronchitis": ["Pulmonologist", "General Practitioner"],
    "migraine": ["Neurologist", "General Practitioner"],
    "sinusitis": ["Otolaryngologist", "General Practitioner"],
    "food_poisoning": ["Gastroenterologist", "General Practitioner"],
    "pregnancy": ["Obstetrician", "Gynecologist"],
    "allergy": ["Allergist", "Immunologist"],
    "hay_fever": ["Allergist", "Immunologist"],
    "anemia": ["Hematologist", "General Practitioner"],
    "diabetes": ["Endocrinologist", "General Practitioner"],
    "thyroid_problems": ["Endocrinologist", "General Practitioner"],
    "heart_attack": ["Cardiologist", "Emergency Medicine Specialist"],
    "angina": ["Cardiologist", "General Practitioner"],
    "pneumonia": ["Pulmonologist", "General Practitioner"],
    "pulmonary_embolism": ["Pulmonologist", "Cardiologist"],
    "asthma": ["Pulmonologist", "Allergist"],
    "COPD": ["Pulmonologist", "General Practitioner"],
    "heart_failure": ["Cardiologist", "General Practitioner"],
    "appendicitis": ["Surgeon", "General Practitioner"],
    "gallstones": ["Gastroenterologist", "Surgeon"],
    "kidney_stones": ["Urologist", "Nephrologist"],
    "ulcers": ["Gastroenterologist", "General Practitioner"],
    "gastroenteritis": ["Gastroenterologist", "General Practitioner"],
    "IBS": ["Gastroenterologist", "Dietitian"],
    "Crohn's_disease": ["Gastroenterologist", "Dietitian"],
    "measles": ["Pediatrician", "General Practitioner"],
    "chickenpox": ["Pediatrician", "General Practitioner"],
    "allergic_reaction": ["Allergist", "Immunologist"],
    "eczema": ["Dermatologist", "Allergist"],
    "arthritis": ["Rheumatologist", "Orthopedic Surgeon"],
    "lupus": ["Rheumatologist", "Immunologist"],
    "gout": ["Rheumatologist", "Nephrologist"],
    "lyme_disease": ["Infectious Disease Specialist", "Rheumatologist"],
    "infection": ["Infectious Disease Specialist", "General Practitioner"],
    "lymphoma": ["Oncologist", "Hematologist"],
    "HIV": ["Infectious Disease Specialist", "General Practitioner"],
    "mononucleosis": ["General Practitioner", "Infectious Disease Specialist"],
    "cancer": ["Oncologist", "Radiation Oncologist"],
    "hyperthyroidism": ["Endocrinologist", "General Practitioner"],
    "menopause": ["Gynecologist", "Endocrinologist"]
};

export const selfCareAdvice = {
    "flu": "Rest, drink plenty of fluids, use fever reducers if needed.",
    "cold": "Stay hydrated, rest, use humidifier, salt water gargle.",
    "COVID-19": "Isolate, rest, stay hydrated, monitor symptoms, seek medical care if worsening.",
    "migraine": "Lie in a dark, quiet room, use cold packs, avoid triggers.",
    "asthma": "Avoid triggers, use prescribed inhalers, monitor breathing.",
    "anemia": "Eat iron-rich foods, take prescribed supplements.",
    "diabetes": "Monitor blood sugar, follow diet, exercise regularly.",
    "allergy": "Avoid allergens, use antihistamines as prescribed.",
    "heart_failure": "Limit salt, monitor weight, follow medication regimen.",
    "ulcers": "Avoid spicy foods, don’t smoke, take prescribed medication.",
    "eczema": "Moisturize regularly, avoid known irritants.",
    "arthritis": "Stay active, use heat/cold therapy, follow prescribed exercises.",
    "measles": "Rest, drink fluids, use fever reducers, avoid close contact.",
    "chickenpox": "Avoid scratching, stay hydrated, use calamine lotion.",
    "gastroenteritis": "Stay hydrated, eat bland foods, rest.",
    "bronchitis": "Avoid smoke, rest, drink fluids.",
    "pneumonia": "Rest, drink fluids, follow doctor’s orders.",
    "dengue": "Rest, drink fluids, avoid NSAIDs.",
    "malaria": "Complete prescribed medication, use mosquito nets.",
    "thyroid_problems": "Take medication as prescribed, regular checkups.",
    "lupus": "Protect from sun, follow medication plan, rest.",
    "appendicitis": "Seek immediate medical care if severe pain.",
    "pregnancy": "Attend regular checkups, take prenatal vitamins, eat healthily.",
    "cancer": "Follow treatment plan, eat well, get support.",
    "mononucleosis": "Get plenty of rest, avoid sports, stay hydrated.",
    "HIV": "Take antiretroviral therapy as prescribed, practice safe habits.",
    "gout": "Limit purine-rich foods, stay hydrated, avoid alcohol.",
    "lymphoma": "Follow treatment, eat healthily, rest, avoid infections.",
    "tuberculosis": "Take medication as prescribed, avoid contact with others.",
    "hyperthyroidism": "Take antithyroid medication, avoid iodine-rich foods.",
    "menopause": "Exercise, eat a balanced diet, manage hot flashes."
};